name: Tap2Tip
favicon: null
layout_spectrum: 0.5679750519338995
typography_spectrum: 0.17648104764521122
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.26830018823966384
  lightness: 0.7316804118454456
  saturation: 0.8299958282150328
  rhythmicContrast: 0.7986495611257851
purpose: []
